// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTC.Data;

#nullable disable

namespace SistemaTC.Data.Migrations
{
    [DbContext(typeof(TCContext))]
    [Migration("20240517045503_RequestNumberIncremental")]
    partial class RequestNumberIncremental
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCard", b =>
                {
                    b.Property<Guid>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("BalanceCutOffDay")
                        .HasColumnType("int");

                    b.Property<string>("Ccv")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<decimal>("ChargeRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CreditAvailable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("Expired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LockedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("NextBalanceCutOffDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NextPaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(19)
                        .IsUnicode(true)
                        .HasColumnType("varchar(19)");

                    b.Property<int>("PaymentDay")
                        .HasColumnType("int");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("CreditCardId");

                    b.HasIndex("Active");

                    b.HasIndex("Number");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCard", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCardTransaction", b =>
                {
                    b.Property<Guid>("CreditCardTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreditCutOffId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("CreditCardTransactionId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("CreditCutOffId");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCardTransaction", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCutOff", b =>
                {
                    b.Property<Guid>("CreditCutOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Closed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("char(36)");

                    b.Property<ushort>("Month")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Payed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PayedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<ushort>("Year")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("CreditCutOffId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCutOff", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreditCutOffId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("CreditCutOffId");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("Active");

                    b.HasIndex("Code");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("56c83f0f-53e0-4328-9ea7-9787bbcbfd02"),
                            Code = "VIEW_USER",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "View User"
                        },
                        new
                        {
                            PermissionId = new Guid("ef127738-9162-4654-89fc-d201386397f0"),
                            Code = "CREATE_USER",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Create User"
                        },
                        new
                        {
                            PermissionId = new Guid("f8072b82-b1b1-4f5c-9eae-f2e7d1bd2634"),
                            Code = "UPDATE_USER",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Update User"
                        },
                        new
                        {
                            PermissionId = new Guid("7280baca-a1b4-42c9-9de2-b837849606a1"),
                            Code = "INACTIVATE_USER",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Inactivate/Activate User"
                        },
                        new
                        {
                            PermissionId = new Guid("c3dd326f-3d61-4a36-934b-2dba1e256b8c"),
                            Code = "VIEW_CREDIT_CARD",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "View Credit Card"
                        },
                        new
                        {
                            PermissionId = new Guid("3d1ea76a-6607-456b-a584-142b32200f74"),
                            Code = "CREATE_CREDIT_CARD",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Create Credit Card"
                        },
                        new
                        {
                            PermissionId = new Guid("b578352c-43d2-49ee-bbd0-c03d6f57e666"),
                            Code = "UPDATE_CREDIT_CARD",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Update Credit Card"
                        },
                        new
                        {
                            PermissionId = new Guid("4dadda0a-30a8-4fe7-83a2-936d9bf236b2"),
                            Code = "INACTIVATE_CREDIT_CARD",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Inactivate/Activate Credit Card"
                        },
                        new
                        {
                            PermissionId = new Guid("ea36832a-eaca-40e6-afbd-dbc9c965a54f"),
                            Code = "UPDATE_PIN_CREDIT_CARD",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Update PIN of Credit Card"
                        },
                        new
                        {
                            PermissionId = new Guid("002622c7-4619-4679-b084-fb16f892f557"),
                            Code = "VIEW_REQUEST",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "View Request"
                        },
                        new
                        {
                            PermissionId = new Guid("abbfb829-aebf-4548-a89d-97570d11c04c"),
                            Code = "CREATE_REQUEST",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Create Request"
                        },
                        new
                        {
                            PermissionId = new Guid("d72db557-1203-48c2-866b-ba41d2f50447"),
                            Code = "UPDATE_REQUEST",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Update Request"
                        },
                        new
                        {
                            PermissionId = new Guid("eda6a773-8c6b-48ec-aa9c-f81be8b46ea2"),
                            Code = "PROCESS_REQUEST",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Process Request"
                        },
                        new
                        {
                            PermissionId = new Guid("33f7e6e5-458c-4f20-84ad-8407570fd568"),
                            Code = "CREATE_CC_TRANSACTION",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Create Credit/Debit Credit Card Transaction"
                        },
                        new
                        {
                            PermissionId = new Guid("a38e0d18-6814-4e71-aa55-f66307bcd93b"),
                            Code = "VIEW_CREDIT_CARD_CUTOFF",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "View Credit Card Cutoff"
                        },
                        new
                        {
                            PermissionId = new Guid("b8c1ee6e-393d-47e1-a58d-5bdb35e69b13"),
                            Code = "CREATE_CREDIT_CARD_CUTOFF",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Create Credit Card Cutoff"
                        },
                        new
                        {
                            PermissionId = new Guid("d21347ca-1c8b-49b6-8694-829801012975"),
                            Code = "UPDATE_CREDIT_CARD_CUTOFF",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Update Credit Card Cutoff"
                        },
                        new
                        {
                            PermissionId = new Guid("54978218-8f88-49e3-93fa-f7b4c2dd2c96"),
                            Code = "VIEW_CREDIT_CARD_PAYMENT",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "View Credit Card Payment"
                        },
                        new
                        {
                            PermissionId = new Guid("c89fe7b5-bb41-44fd-a726-377095491585"),
                            Code = "CREATE_CREDIT_CARD_PAYMENT",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Create Credit Card Payment"
                        },
                        new
                        {
                            PermissionId = new Guid("16d64a71-9d53-4672-bd88-c9dbfd237172"),
                            Code = "VIEW_CREDIT_CARD_INFO_FROM_USER",
                            Created = new DateTime(2024, 5, 14, 1, 24, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "View Credit Card Info from other user"
                        });
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Request", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InternalNote")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RequestId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("Number");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Type");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("Active");

                    b.HasIndex("Code");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            Code = "admin",
                            Created = new DateTime(2024, 5, 11, 0, 36, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("56c83f0f-53e0-4328-9ea7-9787bbcbfd02")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("ef127738-9162-4654-89fc-d201386397f0")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("f8072b82-b1b1-4f5c-9eae-f2e7d1bd2634")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("7280baca-a1b4-42c9-9de2-b837849606a1")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("c3dd326f-3d61-4a36-934b-2dba1e256b8c")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("3d1ea76a-6607-456b-a584-142b32200f74")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("b578352c-43d2-49ee-bbd0-c03d6f57e666")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("4dadda0a-30a8-4fe7-83a2-936d9bf236b2")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("ea36832a-eaca-40e6-afbd-dbc9c965a54f")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("002622c7-4619-4679-b084-fb16f892f557")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("abbfb829-aebf-4548-a89d-97570d11c04c")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("d72db557-1203-48c2-866b-ba41d2f50447")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("eda6a773-8c6b-48ec-aa9c-f81be8b46ea2")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("33f7e6e5-458c-4f20-84ad-8407570fd568")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("a38e0d18-6814-4e71-aa55-f66307bcd93b")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("b8c1ee6e-393d-47e1-a58d-5bdb35e69b13")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("d21347ca-1c8b-49b6-8694-829801012975")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("54978218-8f88-49e3-93fa-f7b4c2dd2c96")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("c89fe7b5-bb41-44fd-a726-377095491585")
                        },
                        new
                        {
                            RoleId = new Guid("e9f77193-3d01-4a99-aa01-6fc777d5a87a"),
                            PermissionId = new Guid("16d64a71-9d53-4672-bd88-c9dbfd237172")
                        });
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(true)
                        .HasColumnType("varchar(15)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Active");

                    b.HasIndex("Email");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.UserToken", b =>
                {
                    b.Property<Guid>("UserTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserTokenId");

                    b.HasIndex("Active");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCard", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.User", "Owner")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCardTransaction", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.CreditCard", "CreditCard")
                        .WithMany("CreditCardTransactions")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTC.Data.Entities.CreditCutOff", "CreditCutOff")
                        .WithMany("CreditCardTransactions")
                        .HasForeignKey("CreditCutOffId");

                    b.HasOne("SistemaTC.Data.Entities.User", "Owner")
                        .WithMany("CreditCardTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("CreditCutOff");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCutOff", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.CreditCard", "CreditCard")
                        .WithMany("CreditCutOffs")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTC.Data.Entities.User", "Owner")
                        .WithMany("CreditCutOffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Payment", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.CreditCard", "CreditCard")
                        .WithMany("Payments")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTC.Data.Entities.CreditCutOff", "CreditCutOff")
                        .WithMany("Payments")
                        .HasForeignKey("CreditCutOffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTC.Data.Entities.User", "Owner")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("CreditCutOff");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Request", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.User", "AssignedTo")
                        .WithMany("RequestsAssigned")
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("SistemaTC.Data.Entities.User", "RequestedBy")
                        .WithMany("Requests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTC.Data.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.User", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.UserToken", b =>
                {
                    b.HasOne("SistemaTC.Data.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCard", b =>
                {
                    b.Navigation("CreditCardTransactions");

                    b.Navigation("CreditCutOffs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.CreditCutOff", b =>
                {
                    b.Navigation("CreditCardTransactions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SistemaTC.Data.Entities.User", b =>
                {
                    b.Navigation("CreditCardTransactions");

                    b.Navigation("CreditCards");

                    b.Navigation("CreditCutOffs");

                    b.Navigation("Payments");

                    b.Navigation("Requests");

                    b.Navigation("RequestsAssigned");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
