@SistemaTC.Api_HostAddress = http://localhost:5154/api

GET {{SistemaTC.Api_HostAddress}}/health-check/
Accept: application/json

###

GET {{SistemaTC.Api_HostAddress}}/User/
Accept: application/json

###

POST {{SistemaTC.Api_HostAddress}}/Notification/mail
Accept: application/json

###
