@SistemaTC.Api_HostAddress = http://localhost:5154/api

GET {{SistemaTC.Api_HostAddress}}/health-check/
Accept: application/json

###

POST {{SistemaTC.Api_HostAddress}}/Notification/mail
Accept: application/json

###

GET {{SistemaTC.Api_HostAddress}}/Request
Accept: application/json

###

GET {{SistemaTC.Api_HostAddress}}/Request/{requestId}
Accept: application/json

###

POST {{SistemaTC.Api_HostAddress}}/Request
Accept: application/json

###

GET {{SistemaTC.Api_HostAddress}}/User/
Accept: application/json

###

GET {{SistemaTC.Api_HostAddress}}/User/{userId}
Accept: application/json

###

POST {{SistemaTC.Api_HostAddress}}/User/Login
Accept: application/json

###

POST {{SistemaTC.Api_HostAddress}}/User/
Accept: application/json

###

PUT {{SistemaTC.Api_HostAddress}}/User/
Accept: application/json

###

PATCH {{SistemaTC.Api_HostAddress}}/User/
Accept: application/json

###
